library(mlbench)
data(Glass)
Glass<-Glass[!duplicated(Glass),]
x<-as.data.frame(Glass)

Q1<-quantile(x$RI,0.25)
Q2<-quantile(x$RI,0.75)
y<-IQR(x$RI)
high1<-Q2+(1.5*y)
low1<-Q1-(1.5*y)

Q1<-quantile(x$Na,0.25)
Q2<-quantile(x$Na,0.75)
y<-IQR(x$Na)
high2<-Q2+(1.5*y)
low2<-Q1-(1.5*y)

Q1<-quantile(x$Mg,0.25)
Q2<-quantile(x$Mg,0.75)
y<-IQR(x$Mg)
high3<-Q2+(1.5*y)
low3<-Q1-(1.5*y)

Q1<-quantile(x$Al,0.25)
Q2<-quantile(x$Al,0.75)
y<-IQR(x$Al)
high4<-Q2+(1.5*y)
low4<-Q1-(1.5*y)

Q1<-quantile(x$Si,0.25)
Q2<-quantile(x$Si,0.75)
y<-IQR(x$Si)
high5<-Q2+(1.5*y)
low5<-Q1-(1.5*y)

Q1<-quantile(x$K,0.25)
Q2<-quantile(x$K,0.75)
y<-IQR(x$K)
high6<-Q2+(1.5*y)
low6<-Q1-(1.5*y)

Q1<-quantile(x$Ca,0.25)
Q2<-quantile(x$Ca,0.75)
y<-IQR(x$Ca)
high7<-Q2+(1.5*y)
low7<-Q1-(1.5*y)

Q1<-quantile(x$Ba,0.25)
Q2<-quantile(x$Ba,0.75)
y<-IQR(x$Ba)
high8<-Q2+(1.5*y)
low8<-Q1-(1.5*y)

Q1<-quantile(x$Fe,0.25)
Q2<-quantile(x$Fe,0.75)
y<-IQR(x$Fe)
high9<-Q2+(1.5*y)
low9<-Q1-(1.5*y)

x_new<-subset(x,x$RI>low1 & x$RI<high1 & x$Na>low2 & x$Na<high2 & x$Mg>low3 & x$Mg<high3 & x$Al>low4 & x$Al<high4 & x$Si>low5 & x$Si<high5 & x$K>low6 & x$K<high6 & x$Ca>low7 & x$Ca<high7 & x$Ba==0 & x$Fe>low9 & x$Fe<high9)

par(mfrow=c(1,9))
par(mar=c(2,2,2,2))

a1<-fivenum(x$RI,na.rm=TRUE)
b1<-fivenum(x$Na,na.rm=TRUE)
c1<-fivenum(x$Mg,na.rm=TRUE)
d1<-fivenum(x$Al,na.rm=TRUE)
e1<-fivenum(x$Si,na.rm=TRUE)
f1<-fivenum(x$K,na.rm=TRUE)
g1<-fivenum(x$Ca,na.rm=TRUE)
h1<-fivenum(x$Ba,na.rm=TRUE)
i1<-fivenum(x$Fe,na.rm=TRUE)

a2<-fivenum(x_new$RI,na.rm=TRUE)
b2<-fivenum(x_new$Na,na.rm=TRUE)
c2<-fivenum(x_new$Mg,na.rm=TRUE)
d2<-fivenum(x_new$Al,na.rm=TRUE)
e2<-fivenum(x_new$Si,na.rm=TRUE)
f2<-fivenum(x_new$K,na.rm=TRUE)
g2<-fivenum(x_new$Ca,na.rm=TRUE)
h2<-fivenum(x_new$Ba,na.rm=TRUE)
i2<-fivenum(x_new$Fe,na.rm=TRUE)

boxplot(a1,a2,horizontal=TRUE,names=c("old","new"),col=c("red","red"),main="RI")
boxplot(b1,b2,horizontal=TRUE,names=c("old","new"),col=c("blue","blue"),main="Na")
boxplot(c1,c2,horizontal=TRUE,names=c("old","new"),col=c("green","green"),main="Mg")
boxplot(d1,d2,horizontal=TRUE,names=c("old","new"),col=c("yellow","yellow"),main="Al")
boxplot(e1,e2,horizontal=TRUE,names=c("old","new"),col=c("pink","pink"),main="Si")
boxplot(f1,f2,horizontal=TRUE,names=c("old","new"),col=c("black","black"),main="K")
boxplot(g1,g2,horizontal=TRUE,names=c("old","new"),col=c("orange","orange"),main="Ca")
boxplot(h1,h2,horizontal=TRUE,names=c("old","new"),col=c("brown","brown"),main="Ba")
boxplot(i1,i2,horizontal=TRUE,names=c("old","new"),col=c("grey","grey"),main="Fe")

